version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: cms-distro
    environment:
      - TZ=Asia/Jakarta
    restart: always
    ports:
      - 8888:80
